#!/bin/bash
# AEGIS-SIGMA setup wizard — configures Strike URL, backend, and data consent.
# Run interactively after first install or to reconfigure.

CONFIG="/etc/aegis-sigma/.env"

echo ""
echo "  ╔═══════════════════════════════════════════════╗"
echo "  ║     AEGIS-SIGMA Setup Wizard                  ║"
echo "  ╚═══════════════════════════════════════════════╝"
echo ""

# ── Data Collection Consent ──────────────────────────────────────
echo "  AEGIS-SIGMA collects anonymized threat data (attack patterns,"
echo "  IP fingerprints, classification results) to improve model"
echo "  accuracy across the network. No personal data, no browsing"
echo "  history, no content — only security telemetry."
echo ""
echo "    1) Enable telemetry (recommended) — helps improve protection"
echo "    2) Disable telemetry — local only, no data shared"
echo ""
read -p "  Choose [1]: " telemetry_choice
telemetry_choice=${telemetry_choice:-1}

case "$telemetry_choice" in
    1)
        TELEMETRY="true"
        echo "  → Telemetry enabled — thank you for helping improve AEGIS-SIGMA"
        ;;
    2)
        TELEMETRY="false"
        echo "  → Telemetry disabled — fully local operation"
        ;;
    *)
        TELEMETRY="true"
        echo "  → Defaulting to telemetry enabled"
        ;;
esac

echo ""

# ── Strike Server ──────────────────────────────────────────────
echo "  Where should hostile traffic be redirected for"
echo "  fingerprinting and counter-attack?"
echo ""
echo "    1) Aegis-SIGMA hosted GCP strike server (recommended)"
echo "    2) My own strike server"
echo "    3) Local tracker only (no external server)"
echo ""
read -p "  Choose [1]: " strike_choice
strike_choice=${strike_choice:-1}

case "$strike_choice" in
    1)
        STRIKE_URL="http://strike.aegis-sigma.com:8443"
        echo "  → Using Aegis-SIGMA hosted GCP strike server"
        ;;
    2)
        read -p "  Enter your strike server URL (e.g. http://your-server:8443): " STRIKE_URL
        if [ -z "$STRIKE_URL" ]; then
            STRIKE_URL="local"
            echo "  → Empty, defaulting to local only"
        fi
        echo "  → Using: $STRIKE_URL"
        ;;
    3)
        STRIKE_URL="local"
        echo "  → Using local Shield tracker (no external server)"
        ;;
    *)
        STRIKE_URL="local"
        echo "  → Invalid choice, defaulting to local only"
        ;;
esac

echo ""

# ── Backend ────────────────────────────────────────────────────
echo "  What is your origin server URL?"
echo "  (The app/website Shield protects and proxies to)"
echo ""
echo "    Example: http://127.0.0.1:8080"
echo "    Leave empty to use Host header routing (multi-site)"
echo ""
read -p "  Backend URL [leave empty]: " BACKEND_URL
BACKEND_URL=${BACKEND_URL:-}

if [ -n "$BACKEND_URL" ]; then
    echo "  → Backend: $BACKEND_URL"
else
    echo "  → Using Host header routing (multi-site mode)"
fi

echo ""

# ── Your Domain ────────────────────────────────────────────────
read -p "  Your domain (e.g. https://example.com): " PRIMARY_SITE
PRIMARY_SITE=${PRIMARY_SITE:-"http://localhost:8080"}
echo "  → Primary site: $PRIMARY_SITE"

echo ""

# ── Write .env ─────────────────────────────────────────────────
cat > "$CONFIG" <<EOF
# AEGIS-SIGMA configuration — generated by setup wizard
# Re-run: /usr/lib/aegis-sigma/setup-wizard.sh

PRIMARY_SITE=$PRIMARY_SITE
STRIKE_URL=$STRIKE_URL
BACKEND_URL=$BACKEND_URL
TELEMETRY=$TELEMETRY
LLM_BASE_URL=
EMAIL_FROM=shield@localhost
EMAIL_NAME=AEGIS Security
SMTP_HOST=127.0.0.1
SMTP_PORT=25
EOF

chmod 644 "$CONFIG"
echo "  ✓ Configuration saved to $CONFIG"
echo ""

# ── Restart services ──────────────────────────────────────────
echo "  Restarting AEGIS-SIGMA services..."
for svc in aegis-shield-go aegis-bridge-go; do
    systemctl restart "$svc" 2>/dev/null && echo "  ✓ $svc restarted" || echo "  ⚠ $svc restart skipped"
done

echo ""
echo "  ╔═══════════════════════════════════════════════╗"
echo "  ║  Setup complete. Services are running.         ║"
echo "  ║  Config: $CONFIG                              ║"
echo "  ╚═══════════════════════════════════════════════╝"
echo ""
